2019-11-19 00:07:21.009 [error] <0.1416.0> CRASH REPORT Process <0.1416.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:07:21.030 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1415.0>,1,<0.1416.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 00:07:21.577 [error] <0.1422.0> CRASH REPORT Process <0.1422.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:07:21.585 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1421.0>,1,<0.1422.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 00:07:22.191 [error] <0.1426.0> CRASH REPORT Process <0.1426.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:07:22.200 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1425.0>,1,<0.1426.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 00:08:10.223 [error] <0.1472.0> CRASH REPORT Process <0.1472.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:08:10.231 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1471.0>,1,<0.1472.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 00:08:10.805 [error] <0.1476.0> CRASH REPORT Process <0.1476.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:08:10.814 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1475.0>,1,<0.1476.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 00:08:11.392 [error] <0.1480.0> CRASH REPORT Process <0.1480.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:08:11.401 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1479.0>,1,<0.1480.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 00:48:12.745 [error] <0.1466.0> CRASH REPORT Process <0.1466.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:48:12.785 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1465.0>,1,<0.1466.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 00:48:13.425 [error] <0.1470.0> CRASH REPORT Process <0.1470.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:48:13.435 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1469.0>,1,<0.1470.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 00:48:14.706 [error] <0.1474.0> CRASH REPORT Process <0.1474.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:48:14.713 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1473.0>,1,<0.1474.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 00:49:35.278 [error] <0.1491.0> CRASH REPORT Process <0.1491.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"169.254.169.254">>,<<"user-agent">> => <<"AWS Security Scanner">>,<<"x-forwarded-for">> => <<"44.224.22.196">>,<<"x-fo...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:49:35.284 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1490.0>,1,<0.1491.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"169.254.169.254">>,<<"user-agent">> => <<"...">>,...},...}},...},...},...},...},...]},...}}
2019-11-19 00:49:36.179 [error] <0.1495.0> CRASH REPORT Process <0.1495.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"[::ffff:a9fe:a9fe]">>,<<"user-agent">> => <<"AWS Security Scanner">>,<<"x-forwarded-for">> => <<"44.224.22.196">>,<<"x...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:49:36.185 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1494.0>,1,<0.1495.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"[::ffff:a9fe:a9fe]">>,<<"user-agent">> => <<..>>,...},...}},...},...},...},...},...]},...}}
2019-11-19 00:50:13.472 [error] <0.1544.0> CRASH REPORT Process <0.1544.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:50:13.481 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1543.0>,1,<0.1544.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 00:50:15.110 [error] <0.1548.0> CRASH REPORT Process <0.1548.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:50:15.118 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1547.0>,1,<0.1548.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 00:50:17.355 [error] <0.1552.0> CRASH REPORT Process <0.1552.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 00:50:17.363 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1551.0>,1,<0.1552.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 04:31:40.617 [error] <0.2173.0> CRASH REPORT Process <0.2173.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:31:40.656 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2172.0>,1,<0.2173.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 04:31:41.414 [error] <0.2177.0> CRASH REPORT Process <0.2177.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:31:41.423 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2176.0>,1,<0.2177.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 04:31:42.264 [error] <0.2181.0> CRASH REPORT Process <0.2181.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:31:42.272 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2180.0>,1,<0.2181.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 04:40:50.071 [error] <0.2297.0> CRASH REPORT Process <0.2297.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:40:50.080 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2296.0>,1,<0.2297.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 04:40:51.039 [error] <0.2301.0> CRASH REPORT Process <0.2301.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:40:51.047 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2300.0>,1,<0.2301.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 04:40:51.878 [error] <0.2305.0> CRASH REPORT Process <0.2305.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:41:53.828 [error] <0.2351.0> CRASH REPORT Process <0.2351.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:41:53.837 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2350.0>,1,<0.2351.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 04:41:54.591 [error] <0.2355.0> CRASH REPORT Process <0.2355.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:41:54.599 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2354.0>,1,<0.2355.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 04:41:57.019 [error] <0.2359.0> CRASH REPORT Process <0.2359.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:41:57.026 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2358.0>,1,<0.2359.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 04:57:59.824 [error] <0.2729.0> CRASH REPORT Process <0.2729.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.BadFunctionError',term => #{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 15,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"connection">> => <<"upgrade">>,<<"content-length">> => <<"15">>,<<"...">> => ...,...},...}},...},...],...}},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:57:59.834 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2728.0>,1,<0.2729.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.BadFunctionError',term => #{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 15,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<...>>,...},...}},...},...],...}},...},...},...]},...}}
2019-11-19 04:58:23.643 [error] <0.2771.0> CRASH REPORT Process <0.2771.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:58:23.651 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2770.0>,1,<0.2771.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 04:58:24.542 [error] <0.2775.0> CRASH REPORT Process <0.2775.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:58:24.550 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2774.0>,1,<0.2775.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 04:58:25.468 [error] <0.2779.0> CRASH REPORT Process <0.2779.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 04:58:25.476 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2778.0>,1,<0.2779.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 05:02:40.234 [error] <0.2856.0> CRASH REPORT Process <0.2856.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 05:02:40.242 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2855.0>,1,<0.2856.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 05:02:40.902 [error] <0.2860.0> CRASH REPORT Process <0.2860.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 05:02:40.910 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2859.0>,1,<0.2860.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 05:02:41.858 [error] <0.2864.0> CRASH REPORT Process <0.2864.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 05:02:41.866 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2863.0>,1,<0.2864.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 05:25:25.531 [error] <0.3000.0> CRASH REPORT Process <0.3000.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.BadFunctionError',term => #{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 15,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"connection">> => <<"upgrade">>,<<"content-length">> => <<"15">>,<<"...">> => ...,...},...}},...},...],...}},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 05:25:25.538 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.2999.0>,1,<0.3000.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.BadFunctionError',term => #{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.ActionClauseError',args => [#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 15,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<...>>,...},...}},...},...],...}},...},...},...]},...}}
2019-11-19 05:25:45.156 [error] <0.3043.0> CRASH REPORT Process <0.3043.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 05:25:45.164 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.3042.0>,1,<0.3043.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 05:25:45.930 [error] <0.3047.0> CRASH REPORT Process <0.3047.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 05:25:45.937 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.3046.0>,1,<0.3047.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 05:25:46.819 [error] <0.3051.0> CRASH REPORT Process <0.3051.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 05:25:46.828 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.3050.0>,1,<0.3051.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 05:54:13.773 [error] <0.3162.0> CRASH REPORT Process <0.3162.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 05:54:13.781 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.3161.0>,1,<0.3162.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 05:54:15.105 [error] <0.3166.0> CRASH REPORT Process <0.3166.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 05:54:15.113 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.3165.0>,1,<0.3166.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
2019-11-19 05:54:15.935 [error] <0.3170.0> CRASH REPORT Process <0.3170.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Tenant',apartment => #{'__cardinality__' => one,'__field__' => ...,...},...},...],...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-19 05:54:15.943 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.3169.0>,1,<0.3170.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => sdp_call,kind => nil,module => 'Elixir.Signalling.Notifier'},[{'Elixir.Signalling.Notifier',sdp_call,[[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Tenant',source => <<"tenants">>,state => loaded},'__struct__' => ...,...},...],...],...},...]},...},...]},...}}
