2019-09-02 15:50:08.956 [error] <0.958.0> ** Task <0.958.0> terminating
** Started from 'Elixir.Archive.Supervisor'
** When function  == fun Elixir.Archive.StartAllCamerasVisor:run/1
**      arguments == [[]]
** Reason for termination == 
** {#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2405ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,618}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,"lib/ecto/adapters/sql.ex"},{line,551}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,"lib/ecto/repo/queryable.ex"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,"lib/ecto/repo/queryable.ex"},{line,18}]},{'Elixir.Archive.StartAllCamerasVisor',run,1,[{file,"lib/archive/start_all_cameras_visor.ex"},{line,13}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-02 15:50:09.003 [error] <0.958.0> CRASH REPORT Process <0.958.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2405ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618
2019-09-02 15:50:09.004 [error] <0.825.0> Supervisor 'Elixir.Archive.Supervisor' had child 'Elixir.Archive.StartAllCamerasVisor' started with 'Elixir.Archive.StartAllCamerasVisor':start_link([]) at <0.958.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2405ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618 in context child_terminated
2019-09-02 15:50:11.405 [error] <0.411.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 gen_server tzdata_release_updater terminated with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-02 15:50:11.420 [error] <0.411.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 CRASH REPORT Process tzdata_release_updater with 0 neighbours crashed with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-02 15:50:11.421 [error] <0.405.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 Supervisor {<0.405.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Tzdata.ReleaseUpdater' started with 'Elixir.Tzdata.ReleaseUpdater':start_link() at <0.411.0> exit with reason no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73 in context child_terminated
2019-09-05 15:14:52.872 [error] <0.980.0> ** Task <0.980.0> terminating
** Started from 'Elixir.Archive.Supervisor'
** When function  == fun Elixir.Archive.StartAllCamerasVisor:run/1
**      arguments == [[]]
** Reason for termination == 
** {#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2374ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,618}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,"lib/ecto/adapters/sql.ex"},{line,551}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,"lib/ecto/repo/queryable.ex"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,"lib/ecto/repo/queryable.ex"},{line,18}]},{'Elixir.Archive.StartAllCamerasVisor',run,1,[{file,"lib/archive/start_all_cameras_visor.ex"},{line,13}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-05 15:14:52.908 [error] <0.980.0> CRASH REPORT Process <0.980.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2374ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618
2019-09-05 15:14:52.909 [error] <0.847.0> Supervisor 'Elixir.Archive.Supervisor' had child 'Elixir.Archive.StartAllCamerasVisor' started with 'Elixir.Archive.StartAllCamerasVisor':start_link([]) at <0.980.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2374ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618 in context child_terminated
2019-09-06 11:09:22.709 [error] <0.927.0> ** Task <0.927.0> terminating
** Started from 'Elixir.Archive.Supervisor'
** When function  == fun Elixir.Archive.StartAllCamerasVisor:run/1
**      arguments == [[]]
** Reason for termination == 
** {#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2415ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,618}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,"lib/ecto/adapters/sql.ex"},{line,551}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,"lib/ecto/repo/queryable.ex"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,"lib/ecto/repo/queryable.ex"},{line,18}]},{'Elixir.Archive.StartAllCamerasVisor',run,1,[{file,"lib/archive/start_all_cameras_visor.ex"},{line,13}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-06 11:09:22.798 [error] <0.927.0> CRASH REPORT Process <0.927.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2415ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618
2019-09-06 11:09:22.800 [error] <0.794.0> Supervisor 'Elixir.Archive.Supervisor' had child 'Elixir.Archive.StartAllCamerasVisor' started with 'Elixir.Archive.StartAllCamerasVisor':start_link([]) at <0.927.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2415ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618 in context child_terminated
2019-09-06 11:09:25.309 [error] <0.380.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 gen_server tzdata_release_updater terminated with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-06 11:09:25.317 [error] <0.380.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 CRASH REPORT Process tzdata_release_updater with 0 neighbours crashed with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-06 11:09:25.318 [error] <0.374.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 Supervisor {<0.374.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Tzdata.ReleaseUpdater' started with 'Elixir.Tzdata.ReleaseUpdater':start_link() at <0.380.0> exit with reason no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73 in context child_terminated
2019-10-16 18:17:59.206 [error] <0.1008.0>@Elixir.Archive.VideoVisor:create_dir:59 CRASH REPORT Process <0.1008.0> with 0 neighbours crashed with reason: bad argument in 'Elixir.Archive.VideoVisor':create_dir/2 line 59
2019-10-16 18:17:59.206 [error] <0.1009.0>@Elixir.Archive.VideoVisor:create_dir:59 CRASH REPORT Process <0.1009.0> with 0 neighbours crashed with reason: bad argument in 'Elixir.Archive.VideoVisor':create_dir/2 line 59
2019-10-16 18:18:11.013 [error] <0.1153.0> CRASH REPORT Process <0.1153.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-10-16 18:18:11.179 [error] <0.671.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1151.0>,1,<0.1153.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encodin...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-10-16 18:18:11.488 [error] <0.1156.0> CRASH REPORT Process <0.1156.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"origin">> => <<"http://loca...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-10-16 18:18:11.497 [error] <0.671.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1151.0>,2,<0.1156.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"...">>,...},...}},...},...},...},...},...]},...}}
2019-10-16 18:18:11.666 [error] <0.1159.0> CRASH REPORT Process <0.1159.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:40...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-10-16 18:18:11.678 [error] <0.671.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1151.0>,3,<0.1159.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=...">>,...},...}},...},...},...},...},...]},...}}
2019-11-17 15:46:07.222 [error] <0.1609.0> CRASH REPORT Process <0.1609.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',action,2,[{file,"lib/domoapi_intercom_web/controllers/intercom_controller.ex"},{...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 15:46:07.251 [error] <0.732.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiIntercomWeb.Endpoint.HTTP',<0.1608.0>,1,<0.1609.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',...},...]},...},...]},...}}
2019-11-17 15:52:28.934 [error] <0.1634.0> CRASH REPORT Process <0.1634.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',action,2,[{file,"lib/domoapi_intercom_web/controllers/intercom_controller.ex"},{...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 15:52:28.940 [error] <0.732.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiIntercomWeb.Endpoint.HTTP',<0.1633.0>,1,<0.1634.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',...},...]},...},...]},...}}
2019-11-17 15:53:22.119 [error] <0.1642.0> CRASH REPORT Process <0.1642.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',action,2,[{file,"lib/domoapi_intercom_web/controllers/intercom_controller.ex"},{...}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 15:53:22.124 [error] <0.732.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiIntercomWeb.Endpoint.HTTP',<0.1641.0>,1,<0.1642.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented">>,protocol => 'Elixir.Jason.Encoder',value => {}},[{'Elixir.Jason','encode_to_iodata!',2,[{file,"lib/jason.ex"},{line,199}]},{'Elixir.Phoenix.Controller',json,2,[{file,"lib/phoenix/controller.ex"},{line,279}]},{'Elixir.DomoapiIntercomWeb.IntercomController',...},...]},...},...]},...}}
2019-11-17 17:07:43.560 [error] <0.1811.0> CRASH REPORT Process <0.1811.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 17:07:43.599 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1810.0>,1,<0.1811.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-enc...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-17 17:10:20.916 [error] <0.1846.0> CRASH REPORT Process <0.1846.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 200,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"bearer">> => <<"SFMyNTY.g3QAAAABbQAAABZndWFyZGlhbl9kZWZhdWx0X3Rva2VubQAAAYZleUpoYkdjaU9pSklVelV4TWlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKaGRXUWlPaUprYjIxdl...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 17:10:20.924 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1845.0>,1,<0.1846.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 200,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gzip">>,<<"bearer">> => <<"SFMyNTY.g3QAAAABbQAAABZndWFyZGlhbl9kZWZhdWx0...">>,...},...}},...},...},...},...},...]},...}}
2019-11-17 18:40:07.944 [error] <0.1309.0> CRASH REPORT Process <0.1309.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 58,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"upgrade">>,<<"c...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:40:07.985 [error] <0.445.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1308.0>,1,<0.1309.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 58,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0...">>,...},...}},...},...},...},...},...]},...}}
2019-11-17 18:44:36.020 [error] <0.1328.0> CRASH REPORT Process <0.1328.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"deflate, gzip">>,<<"accept-language">> => <<"ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"user-api.domoface.ru">>,<<"user-agent">> => <<"Mozilla/...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:44:36.026 [error] <0.445.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1327.0>,1,<0.1328.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"deflate, gzip">>,<<"accept-language">> => <<"ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4">>,<<"connection">> => <<"...">>,...},...}},...},...},...},...},...]},...}}
2019-11-17 18:53:27.464 [error] <0.1316.0> CRASH REPORT Process <0.1316.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => {ok,<<123,34,99,97,110,100,105,100,97,116,101,34,58,34,65,117,101,32,208,178,209,129,209,143,32,209,133,209,131,208,185,208,189,209,143,32,208,178,208,190,209,128,32,208,178,32,208,183,208,176,208,186,208,190,208,189,208,181,32,208,180,208,176,34,125>>}},[{hackney_request,handle_body,4,[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_request.erl"},{line,318}]},{hackney_request,perform,2,[{file,"/home/..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 18:53:27.497 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1315.0>,1,<0.1316.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => {ok,<<123,34,99,97,110,100,105,100,97,116,101,34,58,34,65,117,101,32,208,178,209,129,209,143,32,209,133,209,131,208,185,208,189,209,143,32,208,178,208,190,209,128,32,208,178,32,208,183,208,176,208,186,208,190,208,189,208,181,32,208,180,208,176,34,125>>}},[{hackney_request,handle_body,4,[{file,"/home/ubuntu/domoapi/domoapi/deps/h..."},...]},...]},...},...]},...}}
2019-11-17 19:13:54.445 [error] <0.1722.0> CRASH REPORT Process <0.1722.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:13:54.456 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1721.0>,1,<0.1722.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:16:23.624 [error] <0.1800.0> CRASH REPORT Process <0.1800.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:16:23.635 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1799.0>,1,<0.1800.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:16:23.722 [error] <0.1803.0> CRASH REPORT Process <0.1803.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:16:23.733 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1802.0>,1,<0.1803.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:16:24.052 [error] <0.1808.0> CRASH REPORT Process <0.1808.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:16:24.061 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1807.0>,1,<0.1808.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:16:24.090 [error] <0.1811.0> CRASH REPORT Process <0.1811.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:16:24.100 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1810.0>,1,<0.1811.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:17:49.981 [error] <0.1334.0> CRASH REPORT Process <0.1334.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:17:49.981 [error] <0.1343.0> CRASH REPORT Process <0.1343.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:17:49.982 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:17:49.982 [error] <0.1339.0> CRASH REPORT Process <0.1339.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:17:50.021 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1331.0>,1,<0.1334.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:21:26.823 [error] <0.1378.0> CRASH REPORT Process <0.1378.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[#{<<"Authorization">> => <<"Token 02c0008114e4a328">>},{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.e..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:21:26.823 [error] <0.1369.0> CRASH REPORT Process <0.1369.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[#{<<"Authorization">> => <<"Token 02c0008114e4a328">>},{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.e..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:21:26.824 [error] <0.1376.0> CRASH REPORT Process <0.1376.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[#{<<"Authorization">> => <<"Token 02c0008114e4a328">>},{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.e..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:21:26.825 [error] <0.1373.0> CRASH REPORT Process <0.1373.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[#{<<"Authorization">> => <<"Token 02c0008114e4a328">>},{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.e..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:21:26.856 [error] <0.456.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1377.0>,1,<0.1378.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[#{<<"Authorization">> => <<"Token 02c0008114e4a328">>},{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],...}}}}],...},...]},...},...]},...}}
2019-11-17 19:27:10.504 [error] <0.1339.0> CRASH REPORT Process <0.1339.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:27:10.504 [error] <0.1337.0> CRASH REPORT Process <0.1337.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:27:10.504 [error] <0.1343.0> CRASH REPORT Process <0.1343.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:27:10.505 [error] <0.1336.0> CRASH REPORT Process <0.1336.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:27:10.550 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1338.0>,1,<0.1339.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:30:15.582 [error] <0.1340.0> CRASH REPORT Process <0.1340.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:30:15.582 [error] <0.1336.0> CRASH REPORT Process <0.1336.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:30:15.582 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:30:15.624 [error] <0.456.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1339.0>,1,<0.1340.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:34:54.219 [error] <0.520.0> Failed to start Ranch listener 'Elixir.DomoapiUserWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,9080}]) for reason eaddrinuse (address already in use)
2019-11-17 19:34:54.250 [error] <0.518.0> Supervisor {<0.518.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.DomoapiUserWeb.Endpoint.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse} in context start_error
2019-11-17 19:34:54.250 [error] <0.520.0> CRASH REPORT Process <0.520.0> with 0 neighbours exited with reason: {listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse} in ranch_acceptors_sup:listen_error/5 line 66
2019-11-17 19:34:54.251 [error] <0.499.0> Supervisor 'Elixir.DomoapiUserWeb.Endpoint' had child {ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'} started with 'Elixir.Phoenix.Endpoint.Cowboy2Adapter':start_link(http, 'Elixir.DomoapiUserWeb.Endpoint', {ranch_listener_sup,start_link,['Elixir.DomoapiUserWeb.Endpoint.HTTP',ranch_tcp,#{max_connections => ...,...},...]}) at undefined exit with reason {shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}} in context start_error
2019-11-17 19:34:54.251 [error] <0.498.0> Supervisor 'Elixir.DomoapiUser.Supervisor' had child 'Elixir.DomoapiUserWeb.Endpoint' started with 'Elixir.DomoapiUserWeb.Endpoint':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}}}} in context start_error
2019-11-17 19:34:54.251 [error] <0.496.0> CRASH REPORT Process <0.496.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.DomoapiUserWeb.Endpoint',{shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}}}}}},{'Elixir.DomoapiUser.Application',start,[normal,[]]}} in application_master:init/4 line 138
2019-11-17 19:37:38.146 [error] <0.520.0> Failed to start Ranch listener 'Elixir.DomoapiUserWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{port,9080}]) for reason eaddrinuse (address already in use)
2019-11-17 19:37:38.172 [error] <0.518.0> Supervisor {<0.518.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.DomoapiUserWeb.Endpoint.HTTP', ranch_tcp) at undefined exit with reason {listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse} in context start_error
2019-11-17 19:37:38.172 [error] <0.520.0> CRASH REPORT Process <0.520.0> with 0 neighbours exited with reason: {listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse} in ranch_acceptors_sup:listen_error/5 line 66
2019-11-17 19:37:38.172 [error] <0.499.0> Supervisor 'Elixir.DomoapiUserWeb.Endpoint' had child {ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'} started with 'Elixir.Phoenix.Endpoint.Cowboy2Adapter':start_link(http, 'Elixir.DomoapiUserWeb.Endpoint', {ranch_listener_sup,start_link,['Elixir.DomoapiUserWeb.Endpoint.HTTP',ranch_tcp,#{max_connections => ...,...},...]}) at undefined exit with reason {shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}} in context start_error
2019-11-17 19:37:38.172 [error] <0.498.0> Supervisor 'Elixir.DomoapiUser.Supervisor' had child 'Elixir.DomoapiUserWeb.Endpoint' started with 'Elixir.DomoapiUserWeb.Endpoint':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}}}} in context start_error
2019-11-17 19:37:38.172 [error] <0.496.0> CRASH REPORT Process <0.496.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.DomoapiUserWeb.Endpoint',{shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.DomoapiUserWeb.Endpoint.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.DomoapiUserWeb.Endpoint.HTTP',eaddrinuse}}}}}}},{'Elixir.DomoapiUser.Application',start,[normal,[]]}} in application_master:init/4 line 138
2019-11-17 19:40:27.700 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:40:27.700 [error] <0.1347.0> CRASH REPORT Process <0.1347.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:40:27.700 [error] <0.1346.0> CRASH REPORT Process <0.1346.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:40:27.701 [error] <0.1340.0> CRASH REPORT Process <0.1340.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:40:27.749 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1343.0>,1,<0.1344.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/dom..."},...]},...]},...},...]},...}}
2019-11-17 19:45:08.035 [error] <0.1333.0> CRASH REPORT Process <0.1333.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:45:08.035 [error] <0.1342.0> CRASH REPORT Process <0.1342.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:45:08.037 [error] <0.1340.0> CRASH REPORT Process <0.1340.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:45:08.037 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:45:08.076 [error] <0.456.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1341.0>,1,<0.1342.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/dom..."},...]},...]},...},...]},...}}
2019-11-17 19:47:59.699 [error] <0.1343.0> CRASH REPORT Process <0.1343.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:47:59.700 [error] <0.1340.0> CRASH REPORT Process <0.1340.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:47:59.701 [error] <0.1336.0> CRASH REPORT Process <0.1336.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:47:59.701 [error] <0.1345.0> CRASH REPORT Process <0.1345.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:47:59.748 [error] <0.456.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1339.0>,1,<0.1340.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/dom..."},...]},...]},...},...]},...}}
2019-11-17 19:50:31.865 [error] <0.1340.0> CRASH REPORT Process <0.1340.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:50:31.865 [error] <0.1343.0> CRASH REPORT Process <0.1343.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:50:31.866 [error] <0.1333.0> CRASH REPORT Process <0.1333.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:50:31.873 [error] <0.1347.0> CRASH REPORT Process <0.1347.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:50:31.914 [error] <0.456.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1342.0>,1,<0.1343.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/dom..."},...]},...]},...},...]},...}}
2019-11-17 19:52:10.285 [error] <0.1335.0> CRASH REPORT Process <0.1335.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:52:10.286 [error] <0.1345.0> CRASH REPORT Process <0.1345.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:52:10.286 [error] <0.1347.0> CRASH REPORT Process <0.1347.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:52:10.286 [error] <0.1342.0> CRASH REPORT Process <0.1342.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_headers_new.erl"},{line,53}]},{lists,foldl,3,[{file,...},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:52:10.334 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1346.0>,1,<0.1347.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => '-from_list/1-fun-0-',kind => nil,module => hackney_headers_new},[{hackney_headers_new,'-from_list/1-fun-0-',[<<"Authorization">>,{0,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}],[{file,"/home/ubuntu/dom..."},...]},...]},...},...]},...}}
2019-11-17 19:55:39.618 [error] <0.1332.0> CRASH REPORT Process <0.1332.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:55:39.619 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:55:39.619 [error] <0.1342.0> CRASH REPORT Process <0.1342.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 230,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:55:39.619 [error] <0.1339.0> CRASH REPORT Process <0.1339.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:55:39.662 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1331.0>,1,<0.1332.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 199,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 19:58:03.992 [error] <0.1338.0> CRASH REPORT Process <0.1338.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 234,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:58:03.992 [error] <0.1342.0> CRASH REPORT Process <0.1342.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:58:03.993 [error] <0.1332.0> CRASH REPORT Process <0.1332.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 201,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:58:03.994 [error] <0.1344.0> CRASH REPORT Process <0.1344.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 19:58:04.035 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1331.0>,1,<0.1332.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 201,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 20:01:14.656 [error] <0.1346.0> CRASH REPORT Process <0.1346.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:01:14.685 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1345.0>,1,<0.1346.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 20:02:37.589 [error] <0.1396.0> CRASH REPORT Process <0.1396.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:02:37.599 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1395.0>,1,<0.1396.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-17 20:03:44.345 [error] <0.1339.0> CRASH REPORT Process <0.1339.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 232,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:03:44.345 [error] <0.1342.0> CRASH REPORT Process <0.1342.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 14,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"gz...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:03:44.346 [error] <0.1337.0> CRASH REPORT Process <0.1337.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 234,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:03:44.347 [error] <0.1332.0> CRASH REPORT Process <0.1332.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 201,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept-charset">> => <<"UTF-8">>,<<"accept-encoding">> => <<"g...">>,...},...}},...},...],...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-17 20:03:44.392 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.1330.0>,1,<0.1332.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 2,clauses => nil,function => call,kind => nil,module => 'Elixir.DomoapiUserWeb.FallbackController'},[{'Elixir.DomoapiUserWeb.FallbackController',call,[#{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 201,cert => undefined,has_body => true,has_read_body => true,...}},...},...],...},...]},...},...]},...}}
2019-11-18 00:00:00.005 [error] <0.1435.0> ** Task <0.1435.0> terminating
** Started from <0.1434.0>
** When function  == #Fun<Elixir.Quantum.Executor.7.12665260>
**      arguments == []
** Reason for termination == 
** {function_clause,[{'Elixir.IO',chardata_to_string,[nil],[{file,"lib/io.ex"},{line,557}]},{'Elixir.File',ls,1,[{file,"lib/file.ex"},{line,1556}]},{'Elixir.Archive.CheckFile',check_dir,0,[{file,"lib/archive/check_file.ex"},{line,8}]},{'Elixir.Quantum.Executor','-run/4-fun-3-',3,[{file,"lib/quantum/executor.ex"},{line,141}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{'Elixir.Task.Supervised',reply,5,[{file,"lib/task/supervised.ex"},{line,35}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-11-18 00:00:00.026 [error] <0.1435.0>@Elixir.IO:chardata_to_string:557 CRASH REPORT Process <0.1435.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':chardata_to_string(nil) line 557
2019-11-18 00:00:00.026 [error] <0.1150.0>@Elixir.IO:chardata_to_string:557 Supervisor 'Elixir.Archive.Scheduler.Task.Supervisor' had child undefined started with {'Elixir.Task.Supervised',start_link,undefined} at <0.1435.0> exit with reason no function clause matching 'Elixir.IO':chardata_to_string(nil) line 557 in context child_terminated
