2019-09-02 15:50:08.956 [error] <0.958.0> ** Task <0.958.0> terminating
** Started from 'Elixir.Archive.Supervisor'
** When function  == fun Elixir.Archive.StartAllCamerasVisor:run/1
**      arguments == [[]]
** Reason for termination == 
** {#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2405ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,618}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,"lib/ecto/adapters/sql.ex"},{line,551}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,"lib/ecto/repo/queryable.ex"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,"lib/ecto/repo/queryable.ex"},{line,18}]},{'Elixir.Archive.StartAllCamerasVisor',run,1,[{file,"lib/archive/start_all_cameras_visor.ex"},{line,13}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-02 15:50:09.003 [error] <0.958.0> CRASH REPORT Process <0.958.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2405ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618
2019-09-02 15:50:09.004 [error] <0.825.0> Supervisor 'Elixir.Archive.Supervisor' had child 'Elixir.Archive.StartAllCamerasVisor' started with 'Elixir.Archive.StartAllCamerasVisor':start_link([]) at <0.958.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2405ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618 in context child_terminated
2019-09-02 15:50:11.405 [error] <0.411.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 gen_server tzdata_release_updater terminated with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-02 15:50:11.420 [error] <0.411.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 CRASH REPORT Process tzdata_release_updater with 0 neighbours crashed with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-02 15:50:11.421 [error] <0.405.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 Supervisor {<0.405.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Tzdata.ReleaseUpdater' started with 'Elixir.Tzdata.ReleaseUpdater':start_link() at <0.411.0> exit with reason no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73 in context child_terminated
2019-09-05 15:14:52.872 [error] <0.980.0> ** Task <0.980.0> terminating
** Started from 'Elixir.Archive.Supervisor'
** When function  == fun Elixir.Archive.StartAllCamerasVisor:run/1
**      arguments == [[]]
** Reason for termination == 
** {#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2374ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,618}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,"lib/ecto/adapters/sql.ex"},{line,551}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,"lib/ecto/repo/queryable.ex"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,"lib/ecto/repo/queryable.ex"},{line,18}]},{'Elixir.Archive.StartAllCamerasVisor',run,1,[{file,"lib/archive/start_all_cameras_visor.ex"},{line,13}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-05 15:14:52.908 [error] <0.980.0> CRASH REPORT Process <0.980.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2374ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618
2019-09-05 15:14:52.909 [error] <0.847.0> Supervisor 'Elixir.Archive.Supervisor' had child 'Elixir.Archive.StartAllCamerasVisor' started with 'Elixir.Archive.StartAllCamerasVisor':start_link([]) at <0.980.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2374ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618 in context child_terminated
2019-09-06 11:09:22.709 [error] <0.927.0> ** Task <0.927.0> terminating
** Started from 'Elixir.Archive.Supervisor'
** When function  == fun Elixir.Archive.StartAllCamerasVisor:run/1
**      arguments == [[]]
** Reason for termination == 
** {#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2415ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,618}]},{'Elixir.Ecto.Adapters.SQL',execute,5,[{file,"lib/ecto/adapters/sql.ex"},{line,551}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,"lib/ecto/repo/queryable.ex"},{line,153}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,"lib/ecto/repo/queryable.ex"},{line,18}]},{'Elixir.Archive.StartAllCamerasVisor',run,1,[{file,"lib/archive/start_all_cameras_visor.ex"},{line,13}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-09-06 11:09:22.798 [error] <0.927.0> CRASH REPORT Process <0.927.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2415ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618
2019-09-06 11:09:22.800 [error] <0.794.0> Supervisor 'Elixir.Archive.Supervisor' had child 'Elixir.Archive.StartAllCamerasVisor' started with 'Elixir.Archive.StartAllCamerasVisor':start_link([]) at <0.927.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<"connection not available and request was dropped from queue after 2415ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information">>} in 'Elixir.Ecto.Adapters.SQL':raise_sql_call_error/1 line 618 in context child_terminated
2019-09-06 11:09:25.309 [error] <0.380.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 gen_server tzdata_release_updater terminated with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-06 11:09:25.317 [error] <0.380.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 CRASH REPORT Process tzdata_release_updater with 0 neighbours crashed with reason: no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73
2019-09-06 11:09:25.318 [error] <0.374.0>@Elixir.Tzdata.Util:first_matching_weekday_in_month:73 Supervisor {<0.374.0>,'Elixir.Supervisor.Default'} had child 'Elixir.Tzdata.ReleaseUpdater' started with 'Elixir.Tzdata.ReleaseUpdater':start_link() at <0.380.0> exit with reason no function clause matching 'Elixir.Tzdata.Util':first_matching_weekday_in_month(1932, 4, 7, []) line 73 in context child_terminated
2019-10-16 18:17:59.206 [error] <0.1008.0>@Elixir.Archive.VideoVisor:create_dir:59 CRASH REPORT Process <0.1008.0> with 0 neighbours crashed with reason: bad argument in 'Elixir.Archive.VideoVisor':create_dir/2 line 59
2019-10-16 18:17:59.206 [error] <0.1009.0>@Elixir.Archive.VideoVisor:create_dir:59 CRASH REPORT Process <0.1009.0> with 0 neighbours crashed with reason: bad argument in 'Elixir.Archive.VideoVisor':create_dir/2 line 59
2019-10-16 18:18:11.013 [error] <0.1153.0> CRASH REPORT Process <0.1153.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-10-16 18:18:11.179 [error] <0.671.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1151.0>,1,<0.1153.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encodin...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-10-16 18:18:11.488 [error] <0.1156.0> CRASH REPORT Process <0.1156.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"origin">> => <<"http://loca...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-10-16 18:18:11.497 [error] <0.671.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1151.0>,2,<0.1156.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"...">>,...},...}},...},...},...},...},...]},...}}
2019-10-16 18:18:11.666 [error] <0.1159.0> CRASH REPORT Process <0.1159.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:40...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-10-16 18:18:11.678 [error] <0.671.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiWeb.Endpoint.HTTP',<0.1151.0>,3,<0.1159.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=...">>,...},...}},...},...},...},...},...]},...}}
2019-11-16 14:16:14.568 [error] <0.8433.0> CRASH REPORT Process <0.8433.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"intercom-api.domoface.ru">>,<<"user-agent">> => <<"Python/3.7 aiohttp/3.6.2">>,<<"x-forwarded-for">> => <<"87.76.0.8">>,<<..>> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-16 14:16:14.604 [error] <0.7574.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiIntercomWeb.Endpoint.HTTP',<0.8432.0>,1,<0.8433.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"intercom-api.domoface.ru">>,<<"...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-16 14:16:52.107 [error] <0.8437.0> CRASH REPORT Process <0.8437.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"intercom-api.domoface.ru">>,<<"user-agent">> => <<"Python/3.7 aiohttp/3.6.2">>,<<"x-forwarded-for">> => <<"87.76.0.8">>,<<..>> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-16 14:16:52.113 [error] <0.7574.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiIntercomWeb.Endpoint.HTTP',<0.8436.0>,1,<0.8437.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"intercom-api.domoface.ru">>,<<"...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-16 14:17:15.806 [error] <0.8441.0> CRASH REPORT Process <0.8441.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"signaling-api.domoface.ru">>,<<"user-agent">> => <<"Python/3.7 aiohttp/3.6.2">>,<<"x-forwarded-for">> => <<"87.76.0.8">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-16 14:17:15.812 [error] <0.7574.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.8440.0>,1,<0.8441.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"signaling-api.domoface.ru">>,<<"u...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-16 14:18:09.185 [error] <0.1318.0> CRASH REPORT Process <0.1318.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"signaling-api.domoface.ru">>,<<"user-agent">> => <<"Python/3.7 aiohttp/3.6.2">>,<<"x-forwarded-for">> => <<"87.76.0.8">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-16 14:18:09.226 [error] <0.462.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1317.0>,1,<0.1318.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"signaling-api.domoface.ru">>,<<"u...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-16 14:19:03.317 [error] <0.1315.0> CRASH REPORT Process <0.1315.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"signaling-api.domoface.ru">>,<<"user-agent">> => <<"Python/3.7 aiohttp/3.6.2">>,<<"x-forwarded-for">> => <<"87.76.0.8">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-16 14:19:03.360 [error] <0.459.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1314.0>,1,<0.1315.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"signaling-api.domoface.ru">>,<<"u...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-16 14:22:11.047 [error] <0.1176.0>@Elixir.Archive.VideoVisor:create_dir:59 CRASH REPORT Process <0.1176.0> with 0 neighbours crashed with reason: bad argument in 'Elixir.Archive.VideoVisor':create_dir/2 line 59
2019-11-16 14:23:45.871 [error] <0.1303.0> CRASH REPORT Process <0.1303.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"signaling-api.domoface.ru">>,<<"user-agent">> => <<"Python/3.7 aiohttp/3.6.2">>,<<"x-forwarded-for">> => <<"87.76.0.8">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-16 14:23:45.913 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1302.0>,1,<0.1303.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"signaling-api.domoface.ru">>,<<"u...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-16 14:25:41.039 [error] <0.1314.0> CRASH REPORT Process <0.1314.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"deflate, gzip">>,<<"accept-language">> => <<"ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"signaling-api.domoface.ru">>,<<"user-agent">> => <<"Moz...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-16 14:25:41.044 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1313.0>,1,<0.1314.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"deflate, gzip">>,<<"accept-language">> => <<"ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4">>,<<"connection">> => <<"...">>,...},...}},...},...},...},...},...]},...}}
2019-11-16 14:37:54.426 [error] <0.1439.0> ** Task <0.1439.0> terminating
** Started from <0.1437.0>
** When function  == fun erlang:apply/2
**      arguments == [#Fun<Elixir.Signalling.Notifier.2.51368664>,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 7,microsecond => {0,0},minute => 16,month => 11,second => 35,year => 2019},serial_key => <<"2a05092ea1c0c777">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"485e8a74-16dd-4055-849c-afe3ce1ba567">>,token => <<"dzo2OFu7SUo:APA91bFnINEJRvcOPNqEWJ03npWSItB4a3lTRL9Y_dmsl0_1uJ4QMvpcdt-6UiWGK6J02xqcbC07AK43f7fsWMYUIurk6PZVDwhEOG_EBwWiTTpU9QhPmsgR4nuq0XM-JHfsavOjHoZ8">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 14,microsecond => {0,0},minute => 37,month => 11,second => 35,year => 2019}}]]
** Reason for termination == 
** {function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 7,microsecond => {0,0},minute => 16,month => 11,second => 35,year => 2019},serial_key => <<"2a05092ea1c0c777">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"485e8a74-16dd-4055-849c-afe3ce1ba567">>,token => <<"dzo2OFu7SUo:APA91bFnINEJRvcOPNqEWJ03npWSItB4a3lTRL9Y_dmsl0_1uJ4QMvpcdt-6UiWGK6J02xqcbC07AK43f7fsWMYUIurk6PZVDwhEOG_EBwWiTTpU9QhPmsgR4nuq0XM-JHfsavOjHoZ8">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 14,microsecond => {0,0},minute => 37,month => 11,second => 35,year => 2019}},{<<"f9512476-c735-445f-bd91-c43cac774a98">>,54515,<<"80710528-57f1-4245-9368-5c0883d1ea1e">>,<<"v=0\r\no=- 3782903869 3782903869 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic:WMS *\r\nm=video 34474 UDP/TLS/RTP/SAVPF 101 97 98 99 100 101 102\r\nc=IN IP4 192.168.1.138\r\na=sendrecv\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=mid:0\r\na=msid:2dca70ae-36c1-4725-b83d-740439f5210f 2c69a9b5-f15b-4b53-aaff-c02d4162e9ec\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc-group:FID 3097009502 2300326039\r\na=ssrc:3097009502 cname:{c5657bf0-d8ae-41bb-8845-46ee2a680313}\r\na=ssrc:2300326039 cname:{c5657bf0-d8ae-41bb-8845-46ee2a680313}\r\na=rtpmap:101 H264/90000\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=fmtp:101 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 goog-remb\r\na=rtpmap:98 rtx/90000\r\na=fmtp:98 apt=97\r\na=rtpmap:99 H264/90000\r\na=rtcp-fb:99 nack\r\na=rtcp-fb:99 nack pli\r\na=rtcp-fb:99 goog-remb\r\na=fmtp:99 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f\r\na=rtpmap:100 rtx/90000\r\na=fmtp:100 apt=99\r\na=rtpmap:101 H264/90000\r\na=rtpmap:102 rtx/90000\r\na=fmtp:102 apt=101\r\na=candidate:70eb3eb482934759e4e5c63f7f807172 1 udp 2130706431 192.168.1.138 34474 typ host\r\na=candidate:19a9a076fb9676f9d82eb150ec7ff028 1 udp 2130706431 192.168.1.137 45717 typ host\r\na=candidate:f90d...">>}],...},...]}
2019-11-16 14:37:54.428 [error] <0.1439.0>@Elixir.Signalling.Notifier:notify_device_about_call:40 CRASH REPORT Process <0.1439.0> with 4 neighbours crashed with reason: no function clause matching 'Elixir.Signalling.Notifier':notify_device_about_call(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, {<<"f9512476-c735-445f-bd91-c43cac774a98">>,54515,<<"80710528-57f1-4245-9368-5c0883d1ea1e">>,<<"v=...">>}) line 40
2019-11-16 14:37:54.432 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1431.0>,1,<0.1432.0>,function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => ...,...},...},...],...},...]]},...}}
2019-11-16 14:38:06.641 [error] <0.1445.0> ** Task <0.1445.0> terminating
** Started from <0.1442.0>
** When function  == fun erlang:apply/2
**      arguments == [#Fun<Elixir.Signalling.Notifier.0.51368664>,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 7,microsecond => {0,0},minute => 16,month => 11,second => 35,year => 2019},serial_key => <<"2a05092ea1c0c777">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"485e8a74-16dd-4055-849c-afe3ce1ba567">>,token => <<"dzo2OFu7SUo:APA91bFnINEJRvcOPNqEWJ03npWSItB4a3lTRL9Y_dmsl0_1uJ4QMvpcdt-6UiWGK6J02xqcbC07AK43f7fsWMYUIurk6PZVDwhEOG_EBwWiTTpU9QhPmsgR4nuq0XM-JHfsavOjHoZ8">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 14,microsecond => {0,0},minute => 37,month => 11,second => 35,year => 2019}}]]
** Reason for termination == 
** {function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_break_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 7,microsecond => {0,0},minute => 16,month => 11,second => 35,year => 2019},serial_key => <<"2a05092ea1c0c777">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"485e8a74-16dd-4055-849c-afe3ce1ba567">>,token => <<"dzo2OFu7SUo:APA91bFnINEJRvcOPNqEWJ03npWSItB4a3lTRL9Y_dmsl0_1uJ4QMvpcdt-6UiWGK6J02xqcbC07AK43f7fsWMYUIurk6PZVDwhEOG_EBwWiTTpU9QhPmsgR4nuq0XM-JHfsavOjHoZ8">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 14,microsecond => {0,0},minute => 37,month => 11,second => 35,year => 2019}}],[{file,"lib/signalling/notifier.ex"},{line,52}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{'Elixir.Task.Supervised',reply,5,[{file,"lib/task/supervised.ex"},{line,35}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-11-16 14:38:06.641 [error] <0.1445.0>@Elixir.Signalling.Notifier:notify_device_about_break_call:52 CRASH REPORT Process <0.1445.0> with 2 neighbours crashed with reason: no function clause matching 'Elixir.Signalling.Notifier':notify_device_about_break_call(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}) line 52
2019-11-16 14:38:06.643 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1441.0>,1,<0.1442.0>,function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_break_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{...},...}],...},...]]},...}}
2019-11-16 14:38:14.143 [error] <0.1456.0> ** Task <0.1456.0> terminating
** Started from <0.1454.0>
** When function  == fun erlang:apply/2
**      arguments == [#Fun<Elixir.Signalling.Notifier.2.51368664>,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 7,microsecond => {0,0},minute => 16,month => 11,second => 35,year => 2019},serial_key => <<"2a05092ea1c0c777">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"485e8a74-16dd-4055-849c-afe3ce1ba567">>,token => <<"dzo2OFu7SUo:APA91bFnINEJRvcOPNqEWJ03npWSItB4a3lTRL9Y_dmsl0_1uJ4QMvpcdt-6UiWGK6J02xqcbC07AK43f7fsWMYUIurk6PZVDwhEOG_EBwWiTTpU9QhPmsgR4nuq0XM-JHfsavOjHoZ8">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 14,microsecond => {0,0},minute => 37,month => 11,second => 35,year => 2019}}]]
** Reason for termination == 
** {function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 7,microsecond => {0,0},minute => 16,month => 11,second => 35,year => 2019},serial_key => <<"2a05092ea1c0c777">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"485e8a74-16dd-4055-849c-afe3ce1ba567">>,token => <<"dzo2OFu7SUo:APA91bFnINEJRvcOPNqEWJ03npWSItB4a3lTRL9Y_dmsl0_1uJ4QMvpcdt-6UiWGK6J02xqcbC07AK43f7fsWMYUIurk6PZVDwhEOG_EBwWiTTpU9QhPmsgR4nuq0XM-JHfsavOjHoZ8">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 14,microsecond => {0,0},minute => 37,month => 11,second => 35,year => 2019}},{<<"0bbd84ea-2a87-445c-95bf-2d1aa6abfe90">>,38841,<<"80710528-57f1-4245-9368-5c0883d1ea1e">>,<<"v=0\r\no=- 3782903893 3782903893 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic:WMS *\r\nm=video 33580 UDP/TLS/RTP/SAVPF 101 97 98 99 100 101 102\r\nc=IN IP4 192.168.1.138\r\na=sendrecv\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=mid:0\r\na=msid:9451b01a-86d3-4fba-884c-a6fcb5fd2b15 e9dd789e-feff-4d72-b227-11d06f5d05eb\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc-group:FID 3410554955 2735288626\r\na=ssrc:3410554955 cname:{03ba4afc-45f4-462e-8243-eaf96723658e}\r\na=ssrc:2735288626 cname:{03ba4afc-45f4-462e-8243-eaf96723658e}\r\na=rtpmap:101 H264/90000\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=fmtp:101 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 goog-remb\r\na=rtpmap:98 rtx/90000\r\na=fmtp:98 apt=97\r\na=rtpmap:99 H264/90000\r\na=rtcp-fb:99 nack\r\na=rtcp-fb:99 nack pli\r\na=rtcp-fb:99 goog-remb\r\na=fmtp:99 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f\r\na=rtpmap:100 rtx/90000\r\na=fmtp:100 apt=99\r\na=rtpmap:101 H264/90000\r\na=rtpmap:102 rtx/90000\r\na=fmtp:102 apt=101\r\na=candidate:70eb3eb482934759e4e5c63f7f807172 1 udp 2130706431 192.168.1.138 33580 typ host\r\na=candidate:19a9a076fb9676f9d82eb150ec7ff028 1 udp 2130706431 192.168.1.137 60645 typ host\r\na=candidate:f90d...">>}],...},...]}
2019-11-16 14:38:14.145 [error] <0.1456.0>@Elixir.Signalling.Notifier:notify_device_about_call:40 CRASH REPORT Process <0.1456.0> with 4 neighbours crashed with reason: no function clause matching 'Elixir.Signalling.Notifier':notify_device_about_call(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, {<<"0bbd84ea-2a87-445c-95bf-2d1aa6abfe90">>,38841,<<"80710528-57f1-4245-9368-5c0883d1ea1e">>,<<"v=...">>}) line 40
2019-11-16 14:38:14.150 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1448.0>,1,<0.1449.0>,function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => ...,...},...},...],...},...]]},...}}
2019-11-16 14:38:49.926 [error] <0.1313.0> ** Task <0.1313.0> terminating
** Started from <0.1311.0>
** When function  == fun erlang:apply/2
**      arguments == [#Fun<Elixir.Signalling.Notifier.2.51368664>,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 7,microsecond => {0,0},minute => 16,month => 11,second => 35,year => 2019},serial_key => <<"2a05092ea1c0c777">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"485e8a74-16dd-4055-849c-afe3ce1ba567">>,token => <<"dzo2OFu7SUo:APA91bFnINEJRvcOPNqEWJ03npWSItB4a3lTRL9Y_dmsl0_1uJ4QMvpcdt-6UiWGK6J02xqcbC07AK43f7fsWMYUIurk6PZVDwhEOG_EBwWiTTpU9QhPmsgR4nuq0XM-JHfsavOjHoZ8">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 14,microsecond => {0,0},minute => 37,month => 11,second => 35,year => 2019}}]]
** Reason for termination == 
** {function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 7,microsecond => {0,0},minute => 16,month => 11,second => 35,year => 2019},serial_key => <<"2a05092ea1c0c777">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"485e8a74-16dd-4055-849c-afe3ce1ba567">>,token => <<"dzo2OFu7SUo:APA91bFnINEJRvcOPNqEWJ03npWSItB4a3lTRL9Y_dmsl0_1uJ4QMvpcdt-6UiWGK6J02xqcbC07AK43f7fsWMYUIurk6PZVDwhEOG_EBwWiTTpU9QhPmsgR4nuq0XM-JHfsavOjHoZ8">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 14,microsecond => {0,0},minute => 37,month => 11,second => 35,year => 2019}},{<<"d3feb5f2-45b3-4ece-a673-3ea91ba69df5">>,42393,<<"80710528-57f1-4245-9368-5c0883d1ea1e">>,<<"v=0\r\no=- 3782903929 3782903929 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic:WMS *\r\nm=video 52219 UDP/TLS/RTP/SAVPF 101 97 98 99 100 101 102\r\nc=IN IP4 192.168.1.138\r\na=sendrecv\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=mid:0\r\na=msid:e17bda5c-f5e8-42c1-86d4-8f122f9cfdf0 b70d49ae-a2d7-43ea-95cf-f68593db76eb\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc-group:FID 1364631062 2816403823\r\na=ssrc:1364631062 cname:{708cf40b-828e-4efd-a19f-611b9bc6dd9f}\r\na=ssrc:2816403823 cname:{708cf40b-828e-4efd-a19f-611b9bc6dd9f}\r\na=rtpmap:101 H264/90000\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=fmtp:101 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 goog-remb\r\na=rtpmap:98 rtx/90000\r\na=fmtp:98 apt=97\r\na=rtpmap:99 H264/90000\r\na=rtcp-fb:99 nack\r\na=rtcp-fb:99 nack pli\r\na=rtcp-fb:99 goog-remb\r\na=fmtp:99 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f\r\na=rtpmap:100 rtx/90000\r\na=fmtp:100 apt=99\r\na=rtpmap:101 H264/90000\r\na=rtpmap:102 rtx/90000\r\na=fmtp:102 apt=101\r\na=candidate:70eb3eb482934759e4e5c63f7f807172 1 udp 2130706431 192.168.1.138 52219 typ host\r\na=candidate:19a9a076fb9676f9d82eb150ec7ff028 1 udp 2130706431 192.168.1.137 35712 typ host\r\na=candidate:f90d...">>}],...},...]}
2019-11-16 14:38:49.954 [error] <0.1313.0>@Elixir.Signalling.Notifier:notify_device_about_call:40 CRASH REPORT Process <0.1313.0> with 4 neighbours crashed with reason: no function clause matching 'Elixir.Signalling.Notifier':notify_device_about_call(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, {<<"d3feb5f2-45b3-4ece-a673-3ea91ba69df5">>,42393,<<"80710528-57f1-4245-9368-5c0883d1ea1e">>,<<"v=...">>}) line 40
2019-11-16 14:38:49.965 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1305.0>,1,<0.1306.0>,function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => ...,...},...},...],...},...]]},...}}
2019-11-16 14:39:04.045 [error] <0.1319.0> ** Task <0.1319.0> terminating
** Started from <0.1316.0>
** When function  == fun erlang:apply/2
**      arguments == [#Fun<Elixir.Signalling.Notifier.0.51368664>,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 7,microsecond => {0,0},minute => 16,month => 11,second => 35,year => 2019},serial_key => <<"2a05092ea1c0c777">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"485e8a74-16dd-4055-849c-afe3ce1ba567">>,token => <<"dzo2OFu7SUo:APA91bFnINEJRvcOPNqEWJ03npWSItB4a3lTRL9Y_dmsl0_1uJ4QMvpcdt-6UiWGK6J02xqcbC07AK43f7fsWMYUIurk6PZVDwhEOG_EBwWiTTpU9QhPmsgR4nuq0XM-JHfsavOjHoZ8">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 14,microsecond => {0,0},minute => 37,month => 11,second => 35,year => 2019}}]]
** Reason for termination == 
** {function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_break_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 7,microsecond => {0,0},minute => 16,month => 11,second => 35,year => 2019},serial_key => <<"2a05092ea1c0c777">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"485e8a74-16dd-4055-849c-afe3ce1ba567">>,token => <<"dzo2OFu7SUo:APA91bFnINEJRvcOPNqEWJ03npWSItB4a3lTRL9Y_dmsl0_1uJ4QMvpcdt-6UiWGK6J02xqcbC07AK43f7fsWMYUIurk6PZVDwhEOG_EBwWiTTpU9QhPmsgR4nuq0XM-JHfsavOjHoZ8">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 14,microsecond => {0,0},minute => 37,month => 11,second => 35,year => 2019}}],[{file,"lib/signalling/notifier.ex"},{line,52}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{'Elixir.Task.Supervised',reply,5,[{file,"lib/task/supervised.ex"},{line,35}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-11-16 14:39:04.046 [error] <0.1319.0>@Elixir.Signalling.Notifier:notify_device_about_break_call:52 CRASH REPORT Process <0.1319.0> with 2 neighbours crashed with reason: no function clause matching 'Elixir.Signalling.Notifier':notify_device_about_break_call(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}) line 52
2019-11-16 14:39:04.048 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1315.0>,1,<0.1316.0>,function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_break_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"17ca9bf3-5882-4acc-8c30-f9b50c9a8543">>,inserted_at => #{...},...}],...},...]]},...}}
2019-11-16 14:48:59.145 [error] <0.1183.0>@Elixir.Archive.VideoVisor:create_dir:59 CRASH REPORT Process <0.1183.0> with 0 neighbours crashed with reason: bad argument in 'Elixir.Archive.VideoVisor':create_dir/2 line 59
2019-11-16 14:49:17.400 [error] <0.1332.0> ** Task <0.1332.0> terminating
** Started from <0.1330.0>
** When function  == #Fun<Elixir.Signalling.2.57182687>
**      arguments == []
** Reason for termination == 
** {badarg,[{erlang,list_to_integer,["0:53aa:64c:424:d35d:a8b3:fff7"],[]},{hackney_url,parse_netloc,2,[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney_url.erl"},{line,236}]},{hackney,request,5,[{file,"/home/ubuntu/domoapi/domoapi/deps/hackney/src/hackney.erl"},{line,346}]},{'Elixir.HTTPoison.Base',request,6,[{file,"lib/httpoison/base.ex"},{line,786}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-11-16 14:49:17.422 [error] <0.1332.0>@hackney_url:parse_netloc:236 CRASH REPORT Process <0.1332.0> with 0 neighbours crashed with reason: bad argument in call to erlang:list_to_integer("0:53aa:64c:424:d35d:a8b3:fff7") in hackney_url:parse_netloc/2 line 236
2019-11-16 15:01:18.640 [error] <0.1372.0> ** Task <0.1372.0> terminating
** Started from <0.1370.0>
** When function  == fun erlang:apply/2
**      arguments == [#Fun<Elixir.Signalling.Notifier.2.51368664>,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"ce3742e4-9965-4278-842a-b0141cfb1f0a">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 15,microsecond => {0,0},minute => 0,month => 11,second => 41,year => 2019},serial_key => <<"9e7225961a706a65">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"8664ff71-6de0-4686-ac92-b658c13bb2e3">>,token => <<"frS0zWvZAZk:APA91bEozCOFnQd-N2SXYNBOnb6JWKxUYLVy_8KyG1LZI7IoytJKUjzUwB2eMAalxsY4CH9le7-6kA24u84qATNZ20b_llM5F4JFsXnkbwY_mNBsASuQlyCRNKhjoToYWkW0M0sb8u-p">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 15,microsecond => {0,0},minute => 0,month => 11,second => 41,year => 2019}}]]
** Reason for termination == 
** {function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"ce3742e4-9965-4278-842a-b0141cfb1f0a">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 15,microsecond => {0,0},minute => 0,month => 11,second => 41,year => 2019},serial_key => <<"9e7225961a706a65">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"8664ff71-6de0-4686-ac92-b658c13bb2e3">>,token => <<"frS0zWvZAZk:APA91bEozCOFnQd-N2SXYNBOnb6JWKxUYLVy_8KyG1LZI7IoytJKUjzUwB2eMAalxsY4CH9le7-6kA24u84qATNZ20b_llM5F4JFsXnkbwY_mNBsASuQlyCRNKhjoToYWkW0M0sb8u-p">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 15,microsecond => {0,0},minute => 0,month => 11,second => 41,year => 2019}},{<<"c9041342-925b-4b58-a04c-5d615b5d35d8">>,47923,<<"80710528-57f1-4245-9368-5c0883d1ea1e">>,<<"v=0\r\no=- 3782905278 3782905278 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic:WMS *\r\nm=video 58602 UDP/TLS/RTP/SAVPF 101 97 98 99 100 101 102\r\nc=IN IP4 192.168.1.138\r\na=sendrecv\r\na=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=mid:0\r\na=msid:f2127bc8-ea14-4f98-ad29-9665a7c6f304 bc317ed2-c8b6-4121-826b-82a5950ac7bf\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc-group:FID 1186315205 3418182820\r\na=ssrc:1186315205 cname:{769c9658-31e3-4116-8297-801362dc5175}\r\na=ssrc:3418182820 cname:{769c9658-31e3-4116-8297-801362dc5175}\r\na=rtpmap:101 H264/90000\r\na=rtcp-fb:101 nack\r\na=rtcp-fb:101 nack pli\r\na=rtcp-fb:101 goog-remb\r\na=fmtp:101 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42e01f\r\na=rtpmap:97 VP8/90000\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 goog-remb\r\na=rtpmap:98 rtx/90000\r\na=fmtp:98 apt=97\r\na=rtpmap:99 H264/90000\r\na=rtcp-fb:99 nack\r\na=rtcp-fb:99 nack pli\r\na=rtcp-fb:99 goog-remb\r\na=fmtp:99 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f\r\na=rtpmap:100 rtx/90000\r\na=fmtp:100 apt=99\r\na=rtpmap:101 H264/90000\r\na=rtpmap:102 rtx/90000\r\na=fmtp:102 apt=101\r\na=candidate:70eb3eb482934759e4e5c63f7f807172 1 udp 2130706431 192.168.1.138 58602 typ host\r\na=candidate:19a9a076fb9676f9d82eb150ec7ff028 1 udp 2130706431 192.168.1.137 48442 typ host\r\na=candidate:f90dd7...">>}],...},...]}
2019-11-16 15:01:18.679 [error] <0.1372.0>@Elixir.Signalling.Notifier:notify_device_about_call:40 CRASH REPORT Process <0.1372.0> with 7 neighbours crashed with reason: no function clause matching 'Elixir.Signalling.Notifier':notify_device_about_call(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}, {<<"c9041342-925b-4b58-a04c-5d615b5d35d8">>,47923,<<"80710528-57f1-4245-9368-5c0883d1ea1e">>,<<"v=...">>}) line 40
2019-11-16 15:01:18.690 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1364.0>,1,<0.1365.0>,function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"ce3742e4-9965-4278-842a-b0141cfb1f0a">>,inserted_at => #{'__struct__' => ...,...},...},...],...},...]]},...}}
2019-11-16 15:01:36.026 [error] <0.1391.0> ** Task <0.1391.0> terminating
** Started from <0.1388.0>
** When function  == fun erlang:apply/2
**      arguments == [#Fun<Elixir.Signalling.Notifier.0.51368664>,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"ce3742e4-9965-4278-842a-b0141cfb1f0a">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 15,microsecond => {0,0},minute => 0,month => 11,second => 41,year => 2019},serial_key => <<"9e7225961a706a65">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"8664ff71-6de0-4686-ac92-b658c13bb2e3">>,token => <<"frS0zWvZAZk:APA91bEozCOFnQd-N2SXYNBOnb6JWKxUYLVy_8KyG1LZI7IoytJKUjzUwB2eMAalxsY4CH9le7-6kA24u84qATNZ20b_llM5F4JFsXnkbwY_mNBsASuQlyCRNKhjoToYWkW0M0sb8u-p">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 15,microsecond => {0,0},minute => 0,month => 11,second => 41,year => 2019}}]]
** Reason for termination == 
** {function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_break_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"ce3742e4-9965-4278-842a-b0141cfb1f0a">>,inserted_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 15,microsecond => {0,0},minute => 0,month => 11,second => 41,year => 2019},serial_key => <<"9e7225961a706a65">>,tenant => #{'__cardinality__' => one,'__field__' => tenant,'__owner__' => 'Elixir.Domoapi.People.Device','__struct__' => 'Elixir.Ecto.Association.NotLoaded'},tenant_id => <<"8664ff71-6de0-4686-ac92-b658c13bb2e3">>,token => <<"frS0zWvZAZk:APA91bEozCOFnQd-N2SXYNBOnb6JWKxUYLVy_8KyG1LZI7IoytJKUjzUwB2eMAalxsY4CH9le7-6kA24u84qATNZ20b_llM5F4JFsXnkbwY_mNBsASuQlyCRNKhjoToYWkW0M0sb8u-p">>,updated_at => #{'__struct__' => 'Elixir.NaiveDateTime',calendar => 'Elixir.Calendar.ISO',day => 16,hour => 15,microsecond => {0,0},minute => 0,month => 11,second => 41,year => 2019}}],[{file,"lib/signalling/notifier.ex"},{line,52}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{'Elixir.Task.Supervised',reply,5,[{file,"lib/task/supervised.ex"},{line,35}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-11-16 15:01:36.027 [error] <0.1391.0>@Elixir.Signalling.Notifier:notify_device_about_break_call:52 CRASH REPORT Process <0.1391.0> with 2 neighbours crashed with reason: no function clause matching 'Elixir.Signalling.Notifier':notify_device_about_break_call(#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => ...,...},...}) line 52
2019-11-16 15:01:36.029 [error] <0.455.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1387.0>,1,<0.1388.0>,function_clause,[{'Elixir.Signalling.Notifier',notify_device_about_break_call,[#{'__meta__' => #{'__struct__' => 'Elixir.Ecto.Schema.Metadata',context => nil,prefix => nil,schema => 'Elixir.Domoapi.People.Device',source => <<"devices">>,state => loaded},'__struct__' => 'Elixir.Domoapi.People.Device',deleted => false,device_type => <<"Android">>,id => <<"ce3742e4-9965-4278-842a-b0141cfb1f0a">>,inserted_at => #{...},...}],...},...]]},...}}
2019-11-16 16:41:50.559 [error] <0.1556.0> CRASH REPORT Process <0.1556.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"connection">> => <<"upgrade">>,<<"host">> => <<"signaling-api.domoface.ru">>,<<"upgr...">> => ...,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-16 16:41:50.596 [error] <0.447.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.SignallingWeb.Endpoint.HTTP',<0.1555.0>,1,<0.1556.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-17 00:00:00.008 [error] <0.2247.0> ** Task <0.2247.0> terminating
** Started from <0.2246.0>
** When function  == #Fun<Elixir.Quantum.Executor.7.12665260>
**      arguments == []
** Reason for termination == 
** {function_clause,[{'Elixir.IO',chardata_to_string,[nil],[{file,"lib/io.ex"},{line,557}]},{'Elixir.File',ls,1,[{file,"lib/file.ex"},{line,1556}]},{'Elixir.Archive.CheckFile',check_dir,0,[{file,"lib/archive/check_file.ex"},{line,8}]},{'Elixir.Quantum.Executor','-run/4-fun-3-',3,[{file,"lib/quantum/executor.ex"},{line,141}]},{'Elixir.Task.Supervised',invoke_mfa,2,[{file,"lib/task/supervised.ex"},{line,90}]},{'Elixir.Task.Supervised',reply,5,[{file,"lib/task/supervised.ex"},{line,35}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-11-17 00:00:00.013 [error] <0.2247.0>@Elixir.IO:chardata_to_string:557 CRASH REPORT Process <0.2247.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.IO':chardata_to_string(nil) line 557
2019-11-17 00:00:00.013 [error] <0.1150.0>@Elixir.IO:chardata_to_string:557 Supervisor 'Elixir.Archive.Scheduler.Task.Supervisor' had child undefined started with {'Elixir.Task.Supervised',start_link,undefined} at <0.2247.0> exit with reason no function clause matching 'Elixir.IO':chardata_to_string(nil) line 557 in context child_terminated
