2019-11-13 18:01:00.869 [error] <0.638.0> CRASH REPORT Process <0.638.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown application: :domoapi_web">>},[{'Elixir.Application',app_dir,1,[{file,"lib/application.ex"},{line,699}]},{'Elixir.PhoenixSwagger.Plug.SwaggerUI',call,2,[{file,"lib/phoenix_swagger/plug/swaggerui.ex"},{line,183}]},{'Elixir.Phoenix.Router.Route',call,2,[{file,"lib/phoenix/router/route.ex"},{line,40}]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.DomoapiUserWeb.Endpoint',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-13 18:01:00.983 [error] <0.408.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.636.0>,1,<0.638.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown application: :domoapi_web">>},[{'Elixir.Application',app_dir,1,[{file,"lib/application.ex"},{line,699}]},{'Elixir.PhoenixSwagger.Plug.SwaggerUI',call,2,[{file,"lib/phoenix_swagger/plug/swaggerui.ex"},{line,183}]},{'Elixir.Phoenix.Router.Route',call,2,[{file,"lib/phoenix/router/route.ex"},{line,40}]},{'Elixir.Phoenix.Router',...},...]},...},...]},...}}
2019-11-13 18:01:01.481 [error] <0.642.0> CRASH REPORT Process <0.642.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"origin">> => <<"http://loca...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-13 18:01:01.491 [error] <0.408.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.636.0>,3,<0.642.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<..>>,...},...}},...},...},...},...},...]},...}}
2019-11-13 18:01:01.623 [error] <0.649.0> CRASH REPORT Process <0.649.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:40...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-13 18:01:01.635 [error] <0.408.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.636.0>,4,<0.649.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-13 18:01:42.273 [error] <0.638.0> CRASH REPORT Process <0.638.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown application: :domoapi_user_web">>},[{'Elixir.Application',app_dir,1,[{file,"lib/application.ex"},{line,699}]},{'Elixir.PhoenixSwagger.Plug.SwaggerUI',call,2,[{file,"lib/phoenix_swagger/plug/swaggerui.ex"},{line,183}]},{'Elixir.Phoenix.Router.Route',call,2,[{file,"lib/phoenix/router/route.ex"},{line,40}]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.DomoapiUserWeb.Endpoint',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-13 18:01:42.332 [error] <0.408.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.636.0>,1,<0.638.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown application: :domoapi_user_web">>},[{'Elixir.Application',app_dir,1,[{file,"lib/application.ex"},{line,699}]},{'Elixir.PhoenixSwagger.Plug.SwaggerUI',call,2,[{file,"lib/phoenix_swagger/plug/swaggerui.ex"},{line,183}]},{'Elixir.Phoenix.Router.Route',call,2,[{file,"lib/phoenix/router/route.ex"},{line,40}]},{'Elixir.Phoenix.Router',...},...]},...},...]},...}}
2019-11-13 18:01:42.727 [error] <0.642.0> CRASH REPORT Process <0.642.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"origin">> => <<"http://loca...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-13 18:01:42.736 [error] <0.408.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.637.0>,1,<0.642.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<..>>,...},...}},...},...},...},...},...]},...}}
2019-11-13 18:01:43.538 [error] <0.649.0> CRASH REPORT Process <0.649.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown application: :domoapi_user_web">>},[{'Elixir.Application',app_dir,1,[{file,"lib/application.ex"},{line,699}]},{'Elixir.PhoenixSwagger.Plug.SwaggerUI',call,2,[{file,"lib/phoenix_swagger/plug/swaggerui.ex"},{line,183}]},{'Elixir.Phoenix.Router.Route',call,2,[{file,"lib/phoenix/router/route.ex"},{line,40}]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.DomoapiUserWeb.Endpoint',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-13 18:01:43.544 [error] <0.408.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.637.0>,2,<0.649.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown application: :domoapi_user_web">>},[{'Elixir.Application',app_dir,1,[{file,"lib/application.ex"},{line,699}]},{'Elixir.PhoenixSwagger.Plug.SwaggerUI',call,2,[{file,"lib/phoenix_swagger/plug/swaggerui.ex"},{line,183}]},{'Elixir.Phoenix.Router.Route',call,2,[{file,"lib/phoenix/router/route.ex"},{line,40}]},{'Elixir.Phoenix.Router',...},...]},...},...]},...}}
2019-11-13 18:01:43.770 [error] <0.653.0> CRASH REPORT Process <0.653.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"origin">> => <<"http://loca...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-13 18:01:43.789 [error] <0.408.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.637.0>,4,<0.653.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<..>>,...},...}},...},...},...},...},...]},...}}
2019-11-13 18:01:44.121 [error] <0.660.0> CRASH REPORT Process <0.660.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown application: :domoapi_user_web">>},[{'Elixir.Application',app_dir,1,[{file,"lib/application.ex"},{line,699}]},{'Elixir.PhoenixSwagger.Plug.SwaggerUI',call,2,[{file,"lib/phoenix_swagger/plug/swaggerui.ex"},{line,183}]},{'Elixir.Phoenix.Router.Route',call,2,[{file,"lib/phoenix/router/route.ex"},{line,40}]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.DomoapiUserWeb.Endpoint',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-13 18:01:44.129 [error] <0.408.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.637.0>,5,<0.660.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown application: :domoapi_user_web">>},[{'Elixir.Application',app_dir,1,[{file,"lib/application.ex"},{line,699}]},{'Elixir.PhoenixSwagger.Plug.SwaggerUI',call,2,[{file,"lib/phoenix_swagger/plug/swaggerui.ex"},{line,183}]},{'Elixir.Phoenix.Router.Route',call,2,[{file,"lib/phoenix/router/route.ex"},{line,40}]},{'Elixir.Phoenix.Router',...},...]},...},...]},...}}
2019-11-13 18:01:44.343 [error] <0.668.0> CRASH REPORT Process <0.668.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"origin">> => <<"http://loca...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-13 18:01:44.364 [error] <0.408.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.636.0>,3,<0.668.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<..>>,...},...}},...},...},...},...},...]},...}}
2019-11-13 18:01:44.457 [error] <0.674.0> CRASH REPORT Process <0.674.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown application: :domoapi_user_web">>},[{'Elixir.Application',app_dir,1,[{file,"lib/application.ex"},{line,699}]},{'Elixir.PhoenixSwagger.Plug.SwaggerUI',call,2,[{file,"lib/phoenix_swagger/plug/swaggerui.ex"},{line,183}]},{'Elixir.Phoenix.Router.Route',call,2,[{file,"lib/phoenix/router/route.ex"},{line,40}]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.DomoapiUserWeb.Endpoint',...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-13 18:01:44.464 [error] <0.408.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.636.0>,4,<0.674.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"unknown application: :domoapi_user_web">>},[{'Elixir.Application',app_dir,1,[{file,"lib/application.ex"},{line,699}]},{'Elixir.PhoenixSwagger.Plug.SwaggerUI',call,2,[{file,"lib/phoenix_swagger/plug/swaggerui.ex"},{line,183}]},{'Elixir.Phoenix.Router.Route',call,2,[{file,"lib/phoenix/router/route.ex"},{line,40}]},{'Elixir.Phoenix.Router',...},...]},...},...]},...}}
2019-11-13 18:01:44.730 [error] <0.678.0> CRASH REPORT Process <0.678.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"origin">> => <<"http://loca...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-13 18:01:44.740 [error] <0.408.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.636.0>,6,<0.678.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<..>>,...},...}},...},...},...},...},...]},...}}
2019-11-15 14:33:03.960 [error] <0.655.0> CRASH REPORT Process <0.655.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-15 14:33:04.056 [error] <0.409.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.653.0>,1,<0.655.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encod...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-15 14:33:04.302 [error] <0.658.0> CRASH REPORT Process <0.658.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"origin">> => <<"http://loca...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-15 14:33:04.318 [error] <0.409.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.653.0>,2,<0.658.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<..>>,...},...}},...},...},...},...},...]},...}}
2019-11-15 14:33:04.516 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:40...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-15 14:33:04.530 [error] <0.409.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.653.0>,3,<0.661.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-15 14:51:02.702 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-15 14:51:02.777 [error] <0.409.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.662.0>,1,<0.664.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encod...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-15 14:51:02.965 [error] <0.667.0> CRASH REPORT Process <0.667.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:4000">>,<<"origin">> => <<"http://loca...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-15 14:51:02.975 [error] <0.409.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.662.0>,2,<0.667.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<..>>,...},...}},...},...},...},...},...]},...}}
2019-11-18 14:30:13.118 [error] <0.801.0> CRASH REPORT Process <0.801.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-18 14:30:13.129 [error] <0.564.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.800.0>,1,<0.801.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encod...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-18 14:30:13.421 [error] <0.805.0> CRASH REPORT Process <0.805.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"192.168.1.122:4000">>,<<"origin">> => <<"http://192....">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-18 14:30:13.424 [error] <0.564.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.800.0>,2,<0.805.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"...">>,...},...}},...},...},...},...},...]},...}}
2019-11-18 14:30:13.754 [error] <0.808.0> CRASH REPORT Process <0.808.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-aliv...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-18 14:30:13.760 [error] <0.564.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.800.0>,3,<0.808.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0....">>,...},...}},...},...},...},...},...]},...}}
2019-11-18 14:30:21.957 [error] <0.812.0> CRASH REPORT Process <0.812.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-18 14:30:21.960 [error] <0.564.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.811.0>,1,<0.812.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encod...">> => ...,...},...}},...},...},...},...},...]},...}}
2019-11-18 14:30:22.163 [error] <0.816.0> CRASH REPORT Process <0.816.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"192.168.1.122:4000">>,<<"origin">> => <<"http://192....">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/2 line 42
2019-11-18 14:30:22.166 [error] <0.564.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.DomoapiUserWeb.Endpoint.HTTP',<0.811.0>,2,<0.816.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7">>,<<"connection">> => <<"...">>,...},...}},...},...},...},...},...]},...}}
